objects/AutoTUDest__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>destinataire__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>destinataire</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Automated Testing Destinataires</label>
</CustomObject>

objects/AutoTUParams__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Cron_Queuer_Job__c</fullName>
        <label>Cron Queuer Job</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cron_Sender_Job__c</fullName>
        <label>Cron Sender Job</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_Url__c</fullName>
        <label>Login Url</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>OAuth_Client_ID__c</fullName>
        <label>OAuth Client ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_Client_Secret__c</fullName>
        <label>OAuth Client Secret</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Automated Testing Parameters</label>
</CustomObject>

classes/AutomatedTestingTestUtils.cls
@isTest
public class AutomatedTestingTestUtils {
	public static void insertAutoTUCS(){
		createCSParameters();
		createCSDests();
	}

	private static void createCSParameters(){
		AutoTUParams__c param = new AutoTUParams__c(
			Login_Url__c = 'https://test.salesforce.com',
			OAuth_Client_ID__c = 'CLIENT_ID_TOKEN',
			OAuth_Client_Secret__c = 'CLIENT_SECRET_TOKEN',
			username__c = 'test@test.com',
			password__c='testpass_token',
			Cron_Queuer_Job__c = '0 0 4 * * ?',
			Cron_Sender_Job__c = '0 0 6 * * ?'
			);
		insert param;
	}

	private static void createCSDests(){
		AutoTUDest__c dest1 = new AutoTUDest__c(Name='1', destinataire__c=Userinfo.getUserId());
		insert dest1;
	}

	public class LoggerCalloutMock implements HttpCalloutMock{
		public HttpResponse respond(HttpRequest req){
			HttpResponse resp = new HttpResponse();
			resp.setHeader('Content-Type', 'application/json');
			resp.setBody('{"access_token":"testing"}');
			return resp;
		}
	}
}